# test/ectotherm.jl
#
# Compares Julia ectotherm thermoregulation against NicheMapR for 4 behavioural scenarios.
# Reference CSVs are generated by test/R/ectotherm_thermoregulate.R and stored in
# test/data/ectotherm/<scenario>/environ.csv and enbal.csv.
#
# Scenarios vary shade_seek and can_solar_orient; all other parameters are fixed to match
# the R script defaults (Ww_g=40, shape=3/DesertIguana, epsilon=0.95, pantmax=3, etc.).

using BiophysicalBehaviour
using BiophysicalGeometry
using HeatExchange
using FluidProperties
using Unitful
using Test
using CSV, DataFrames

@testset "ectotherm thermoregulation (vs NicheMapR)" begin

    # ── Location and time (matching R script) ─────────────────────────────────
    # ALAT=-23°, AMINUT=0.7*60; ALONG=133°, ALMINT=0.9*60; ALTT=579.0
    latitude  = -23.7u"°"
    longitude = 133.9u"°"
    elevation = 579.0u"m"
    days      = [15, 46]
    hours     = collect(0.0:1:23.0)
    nsteps    = length(days) * length(hours)  # 48

    minimum_shade = 0.0
    maximum_shade = 0.9

    # Soil depths and atmospheric heights (matching examples/ectotherm.jl)
    depths  = [0.0, 2.5, 5.0, 10.0, 15.0, 20.0, 30.0, 50.0, 100.0, 200.0]u"cm"
    heights = [1.0, 150.0]u"cm"
    n_nodes = length(depths)

    # ── Load shared NicheMapR microclimate CSVs (written once by R script) ────
    data_dir  = joinpath(@__DIR__, "data", "ectotherm", "baseline")
    r_metout   = CSV.read(joinpath(data_dir, "metout.csv"),   DataFrame)
    r_soil     = CSV.read(joinpath(data_dir, "soil.csv"),     DataFrame)
    r_shadmet  = CSV.read(joinpath(data_dir, "shadmet.csv"),  DataFrame)
    r_shadsoil = CSV.read(joinpath(data_dir, "shadsoil.csv"), DataFrame)

    r_met0   = r_metout[1:nsteps, :]
    r_soil0  = r_soil[1:nsteps, :]
    r_met90  = r_shadmet[1:nsteps, :]
    r_soil90 = r_shadsoil[1:nsteps, :]

    soil_cols = ["D0cm", "D2.5cm", "D5cm", "D10cm", "D15cm",
                 "D20cm", "D30cm", "D50cm", "D100cm", "D200cm"]

    # Static fallbacks for fields not present in NMR CSVs.
    # Soil thermal conductivity = 1.25 W/m/K (Thcond in R) and moisture = 0.2 (SoilMoist_Init).
    k_fallback  = fill(1.25u"W/(m*K)", nsteps, n_nodes)
    rh_fallback = fill(0.2,            nsteps, n_nodes)

    function build_nmr_micro(met_df, soil_df)
        n      = nrow(met_df)
        soil_T = hcat([(soil_df[!, col] .+ 273.15) .* u"K" for col in soil_cols]...)
        profiles = [(
            air_temperature   = [(met_df.TALOC[i] + 273.15)u"K",
                                 (met_df.TAREF[i] + 273.15)u"K"],
            relative_humidity = [met_df.RHLOC[i] / 100.0,
                                 met_df.RH[i]    / 100.0],
            wind_speed        = [met_df.VLOC[i]  * u"m/s",
                                 met_df.VREF[i]  * u"m/s"],
        ) for i in 1:n]
        (
            solar_radiation           = (zenith_angle = met_df.ZEN .* u"°",),
            pressure                  = fill(atmospheric_pressure(elevation), n),
            profile                   = profiles,
            sky_temperature           = (met_df.TSKYC .+ 273.15) .* u"K",
            soil_temperature          = soil_T,
            soil_thermal_conductivity = k_fallback,
            soil_humidity             = rh_fallback,
            global_radiation          = met_df.SOLR .* u"W/m^2",
            diffuse_fraction          = fill(0.1, n),
            reference_temperature     = (met_df.TAREF .+ 273.15) .* u"K",
        )
    end

    nmr_min = build_nmr_micro(r_met0, r_soil0)
    nmr_max = build_nmr_micro(r_met90, r_soil90)

    available_environments = AvailableEnvironments(
        nmr_min, nmr_max, minimum_shade, maximum_shade, depths, heights
    )

    env_pars = example_environment_pars(; elevation)

    rmse(a, b) = sqrt(sum((a .- b).^2) / length(a))

    # ── Common organism parameters (matching R script) ────────────────────────
    # R: Ww_g=40, shape=3, epsilon=0.95, alpha_max=0.9, alpha_min=0.6
    # R: T_F_min=24, T_F_max=34, T_B_min=17.5, T_RB_min=15, T_pref=30, CT_min=6, CT_max=40
    # R: diurn=1, nocturn=1, crepus=1, burrow=1, shdburrow=1, climb=0
    # R: mindepth=3, maxdepth=10, delta_shade=3, pct_cond=0, warmsig=0, pantmax=3, pct_mouth=0 (default)
    common_heat_exchange = example_ectotherm_heat_exchange_traits(;
        conduction_pars_external = example_ectotherm_conduction_pars_external(
            conduction_fraction = 0.0),               # R: pct_cond=0
        evaporation_pars = example_ectotherm_evaporation_pars(
            eye_fraction  = 0.0003,
            skin_wetness  = 0.001),
        radiation_pars = example_ectotherm_radiation_pars(
            α_body_dorsal  = 0.9,
            α_body_ventral = 0.9,
            solar_orientation = Intermediate(),
            ϵ_body_dorsal  = 0.95,
            ϵ_body_ventral = 0.95),                   # R: epsilon=0.95
        respiration_pars = example_ectotherm_respiration_pars(
            mouth_fraction = 0.0),                    # R: pct_mouth default=0
    )

    body = Body(DesertIguana(40.0u"g", 1000.0u"kg/m^3"), Naked())  # R: Ww_g=40, shape=3

    # ── Scenario loop ─────────────────────────────────────────────────────────
    # Each scenario varies shade_seek and can_solar_orient (matching R live/postur flags).
    # R scenario mapping:
    #   baseline   → shade_seek=0, live=1, postur=0  ≡ can_seek_shade=false, can_solar_orient=false
    #   shade      → shade_seek=1, live=1, postur=0  ≡ can_seek_shade=true,  can_solar_orient=false
    #   sun_orient → shade_seek=0, live=2, postur=1  ≡ can_seek_shade=false, can_solar_orient=true
    #   full       → shade_seek=1, live=2, postur=1  ≡ can_seek_shade=true,  can_solar_orient=true
    scenarios = [
        (name = "baseline",   can_seek_shade = false, can_solar_orient = false),
        (name = "shade",      can_seek_shade = true,  can_solar_orient = false),
        (name = "sun_orient", can_seek_shade = false, can_solar_orient = true),
        (name = "full",       can_seek_shade = true,  can_solar_orient = true),
    ]

    for scen in scenarios
        @testset "scenario: $(scen.name)" begin

            organism_traits = example_ectotherm_organism_traits(
                activity_period         = CombinedActivity(Diurnal(), Nocturnal(), Crepuscular()),
                can_climb               = false,
                can_retreat_underground = true,
                depth_min_underground   = 3,          # R: mindepth=3
                Δsoil_signal             = 0.0u"K/hr", # R: warmsig=0
                can_seek_shade          = scen.can_seek_shade,
                can_solar_orient        = scen.can_solar_orient,
                can_change_absorptivity = true,
                can_press_to_ground     = false,
                can_pant                = true,
                pant_max                = 3.0,         # R: pantmax=3
                burrow_shade_mode       = AdaptiveBurrowShade(),  # R: shdburrow=1
                shade_min               = 0.0,
                shade_max               = maximum_shade,
                shade_step              = 0.03,        # R: delta_shade=3
                alpha_min               = 0.6,         # R: alpha_min=0.6
                alpha_max               = 0.9,         # R: alpha_max=0.9
                alpha_step              = 0.003,
                T_active_min            = u"K"(24.0u"°C"),  # R: T_F_min=24
                T_active_max            = u"K"(34.0u"°C"),  # R: T_F_max=34
                T_bask                  = u"K"(17.5u"°C"),  # R: T_B_min=17.5
                T_emerge                = u"K"(15.0u"°C"),  # R: T_RB_min=15
                T_target                = u"K"(30.0u"°C"),  # R: T_pref=30
                T_critical_min          = u"K"(6.0u"°C"),   # R: CT_min=6
                T_critical_max          = u"K"(40.0u"°C"),  # R: CT_max=40
                heat_exchange           = common_heat_exchange,
            )
            organism = Organism(body, organism_traits)
            limits   = thermoregulation(organism)

            # Thermoregulation loop
            results         = NamedTuple[]
            previous_depth = limits.depth.reference
            activity_commenced  = false
            for step in 1:nsteps
                if (step - 1) % 24 == 0
                    activity_commenced = false
                end
                out = thermoregulate(
                    organism, available_environments, limits, env_pars,
                    step, previous_depth; activity_commenced
                )
                previous_depth = out.depth_node
                activity_commenced  = activity_commenced || out.state isa Active || out.state isa Basking
                push!(results, out)
            end

            # Julia outputs
            T_body_C    = [ustrip(u"°C", r.T_core)  for r in results]
            state       = [r.state                  for r in results]
            julia_act   = [s isa Active ? 2 : s isa Basking ? 1 : 0 for s in state]
            jl_Q_solar  = [ustrip(u"W", r.ectotherm_out.enbal.Q_solar)  for r in results]
            jl_Q_ir_in  = [ustrip(u"W", r.ectotherm_out.enbal.Q_ir_in)  for r in results]
            jl_Q_ir_out = [ustrip(u"W", r.ectotherm_out.enbal.Q_ir_out) for r in results]

            # NicheMapR reference
            scen_dir = joinpath(@__DIR__, "data", "ectotherm", scen.name)
            r_env = CSV.read(joinpath(scen_dir, "environ.csv"), DataFrame)[1:nsteps, :]
            r_eb  = CSV.read(joinpath(scen_dir, "enbal.csv"),   DataFrame)[1:nsteps, :]
            r_act = r_env.ACT

            # Body temperature: RMSE < 1.5°C (sun_orient scenarios ~1.25°C due to orientation differences)
            # Activity state agreement ≥ 80%
            @test rmse(T_body_C, r_env.TC) < 1.5
            @test sum(julia_act .== r_act) / nsteps ≥ 0.80

            # Heat fluxes: same NMR microclimate input; solar ~0.35 W RMSE from absorptivity
            # differences between Julia and NicheMapR colour-change algorithms
            @test rmse(jl_Q_solar,  r_eb.QSOL)   < 0.5
            @test rmse(jl_Q_ir_in,  r_eb.QIRIN)  < 0.3
            @test rmse(jl_Q_ir_out, r_eb.QIROUT) < 0.3
        end
    end

end # @testset "ectotherm thermoregulation"
